
Conversation opened. 2 messages. 1 message unread.

Skip to content
Using Gmail with screen readers
1 of 10,862
Coursera Course Actions
Inbox

Greg Jones
7:49 AM (49 minutes ago)
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

Greg Jones <gtjones73@gmail.com>
8:24 AM (14 minutes ago)
to me

name: "CI Workflow"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit test with nose
        run:
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app